# Generated by Django 5.2.1 on 2025-05-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='elements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='project',
            name='css_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='html_code',
            field=models.TextField(blank=True),
        ),
    ]
