# Generated by Django 5.2.1 on 2025-06-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_elements_alter_project_css_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='react_code',
        ),
        migrations.RemoveField(
            model_name='project',
            name='react_css_code',
        ),
        migrations.AddField(
            model_name='project',
            name='isHorizontal',
            field=models.BooleanField(default=False),
        ),
    ]
