# Generated by Django 5.2.1 on 2025-06-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_react_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='react_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='react_css_code',
            field=models.TextField(blank=True),
        ),
    ]
